#!/usr/bin/env bash
set -euo pipefail

# Run from here
cd "$(dirname "$0")"

# Build boot files

cd ChezScheme
git submodule update --init --filter=blob:none --recursive
git clean -fxd
./configure --force --pb
make bin/zuo
for M in a6le a6osx arm64le arm64osx
do bin/zuo pb bootquick --host-scheme scheme ${M} # Remove '--host-scheme scheme' to use pb
done
cd ..

# Copy boot files
rsync -av --delete --exclude=pb ChezScheme/boot .
