#!/usr/bin/env bash
set -euo pipefail

# Run from here
cd "$(dirname "$0")"

# Build boot files

cd ChezScheme
git clean -ffxd
git submodule update --init --filter=blob:none --recursive
./configure --force --nothreads --disable-x11
make re.boot
make
for M in a6le a6osx arm64le arm64osx
do make boot XM=${M}
done
cd ..

# Copy boot files
rsync -av --delete --exclude=pb ChezScheme/boot .
